version: '3'
services:
  tiktak:
    build: .
    ports:
      - "4000:4000"
    restart: always
    volumes:
      - ./public:/app/public
    depends_on:
      - db
  db:
    image: mysql:8.0.17
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tiktak
